import { defineConfig, devices } from '@playwright/test'

/**
 * Configuration of the end-to-end tests of the `verify-e2e` cycle.
 *
 * It is ready before an interface exists. While there is none, phase 1 of `verify-e2e` detects the
 * missing navigable surface and stops the cycle before generating any test.
 *
 * The base URL and the command that brings the app up are read from the environment instead of
 * being fixed: when the interface shows up they are filled in here or passed as a variable,
 * without touching the tests.
 *
 * If the surface is static (an HTML generated by a script, no server) `webServer` isn't needed:
 * leave `E2E_WEB_SERVER` undefined and have the specs open the file directly with `file://` —
 * there is nothing to bring up or wait for.
 */

const baseURL = process.env.E2E_BASE_URL ?? 'http://localhost:5173'
const webServerCommand = process.env.E2E_WEB_SERVER

export default defineConfig({
  // One directory per spec: end2end/YYYY-MM-DD-<feature>/e1-<topic>.spec.ts
  testDir: 'end2end',

  // No retries, on purpose. A case that passes on the second attempt is a finding —the test is
  // flaky— and `e2e-triager` has to see it as such, not as a resolved case.
  retries: 0,
  fullyParallel: true,
  forbidOnly: !!process.env.CI,

  // The report the triager reads to diagnose: `list` in the console and the JSON with the detail
  // per case. It doesn't open the HTML report on its own, which hangs the process in an agent run.
  reporter: [['list'], ['json', { outputFile: 'end2end/.results/results.json' }]],

  use: {
    baseURL,
    // 'retain-on-failure' and not 'on-first-retry': with retries: 0 above, a retry never happens,
    // so 'on-first-retry' never records anything — the triager ends up diagnosing without a trace.
    // Here it is recorded on the first and only attempt if it fails.
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
  },

  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],

  // Enabled only if E2E_WEB_SERVER says how to bring the app up. While it doesn't exist, Playwright
  // doesn't try to start anything and the failure is clear instead of a two-minute timeout.
  ...(webServerCommand
    ? { webServer: { command: webServerCommand, url: baseURL, reuseExistingServer: !process.env.CI } }
    : {}),
})
